version: "3"
services: 
    app:
        container_name: apimodelos
        restart: always
        build: .
        ports: 
            - "4000:3000"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27018:27017"